kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: insightfinder-agent
spec:
  template:
    metadata:
      labels:
        component: daemonset
    spec:
      containers:
        - name: insightfinder
          image: insightfinderagent/kubernetes-daemon-set:testing
          command: [ "bash", "-c", "/startup.sh" ]
          env:
            - name: INSIGHTFINDER_PROJECTKEY
              value: "35f2a8a9ec0650afc93e4f308a8179f497e635f8"
            - name: INSIGHTFINDER_USERNAME
              value: "insightuser"
            - name: SAMPLING_INTERVAL
              value: "1"
            - name: REPORTING_INTERVAL
              value: "2"
            - name: AGENT
              value: "daemonset"
          volumeMounts:
            - name: run
              mountPath: /var/run/docker.sock
            - name: list
              mountPath: /var/lib/docker/containers
            - name: timezone
              mountPath: /etc/timezone
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
      volumes:
            - name: run
              hostPath:
                  path: /var/run/docker.sock
            - name: list
              hostPath:
                  path: /var/lib/docker/containers
            - name: timezone
              hostPath:
                  path: /etc/localtime
